workspace(name = "sekai-private")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "sekai-best-music-metas",
    downloaded_file_path = "music_metas.json",
    url = "https://storage.sekai.best/sekai-best-assets/music_metas.json",
)
