proto_library(
    name = "action_set_lottery_condition_proto",
    srcs = ["action_set_lottery_condition.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "action_set_lottery_condition_cc_proto",
    deps = [":action_set_lottery_condition_proto"],
)

proto_library(
    name = "area_spirit_world_tree_proto",
    srcs = ["area_spirit_world_tree.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "area_spirit_world_tree_cc_proto",
    deps = [":area_spirit_world_tree_proto"],
)

proto_library(
    name = "card_supplie_proto",
    srcs = ["card_supplie.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "card_supplie_cc_proto",
    deps = [":card_supplie_proto"],
)

proto_library(
    name = "card_supply_group_proto",
    srcs = ["card_supply_group.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "card_supply_group_cc_proto",
    deps = [":card_supply_group_proto"],
)

proto_library(
    name = "character_mission_v2_ex_json_proto",
    srcs = ["character_mission_v2_ex_json.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "character_mission_v2_ex_json_cc_proto",
    deps = [":character_mission_v2_ex_json_proto"],
)

proto_library(
    name = "gacha_bonus_item_receivable_reward_proto",
    srcs = ["gacha_bonus_item_receivable_reward.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "gacha_bonus_item_receivable_reward_cc_proto",
    deps = [":gacha_bonus_item_receivable_reward_proto"],
)

proto_library(
    name = "gacha_bonus_reward_item_group_proto",
    srcs = ["gacha_bonus_reward_item_group.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "gacha_bonus_reward_item_group_cc_proto",
    deps = [":gacha_bonus_reward_item_group_proto"],
)

proto_library(
    name = "gacha_freebie_group_proto",
    srcs = ["gacha_freebie_group.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "gacha_freebie_group_cc_proto",
    deps = [":gacha_freebie_group_proto"],
)

proto_library(
    name = "home_exchange_button_proto",
    srcs = ["home_exchange_button.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "home_exchange_button_cc_proto",
    deps = [":home_exchange_button_proto"],
)

proto_library(
    name = "honor_mission_type_order_proto",
    srcs = ["honor_mission_type_order.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "honor_mission_type_order_cc_proto",
    deps = [":honor_mission_type_order_proto"],
)

proto_library(
    name = "release_condition_logical_expression_proto",
    srcs = ["release_condition_logical_expression.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "release_condition_logical_expression_cc_proto",
    deps = [":release_condition_logical_expression_proto"],
)

proto_library(
    name = "story_mission_proto",
    srcs = ["story_mission.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "story_mission_cc_proto",
    deps = [":story_mission_proto"],
)
