proto_library(
    name = "ad_reward_proto",
    srcs = ["ad_reward.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "ad_reward_cc_proto",
    deps = [":ad_reward_proto"],
)

proto_library(
    name = "character_archive_voice_proto",
    srcs = ["character_archive_voice.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "character_archive_voice_cc_proto",
    deps = [":character_archive_voice_proto"],
)

proto_library(
    name = "character_archive_voice_tag_proto",
    srcs = ["character_archive_voice_tag.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "character_archive_voice_tag_cc_proto",
    deps = [":character_archive_voice_tag_proto"],
)

proto_library(
    name = "event_mission_selectable_reward_proto",
    srcs = ["event_mission_selectable_reward.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "event_mission_selectable_reward_cc_proto",
    deps = [":event_mission_selectable_reward_proto"],
)

proto_library(
    name = "live_clear_voice_proto",
    srcs = ["live_clear_voice.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "live_clear_voice_cc_proto",
    deps = [":live_clear_voice_proto"],
)

proto_library(
    name = "material_auto_exchange_music_vocal_proto",
    srcs = ["material_auto_exchange_music_vocal.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "material_auto_exchange_music_vocal_cc_proto",
    deps = [":material_auto_exchange_music_vocal_proto"],
)

proto_library(
    name = "asset_list_proto",
    srcs = ["asset_list.proto"],
    deps = [":descriptor_proto"],
)

cc_proto_library(
    name = "asset_list_cc_proto",
    deps = [":asset_list_proto"],
)
